CREATE TABLE NOTETAKER.WORKSPACE_MEMBER
(
    WORKSPACE_MEMBER_ID NUMBER       GENERATED ALWAYS AS IDENTITY,
    WORKSPACE_ID        NUMBER       NOT NULL,
    USER_ID             NUMBER       NOT NULL,
    ROLE_CD             VARCHAR2(10) NOT NULL,  -- OWNER / EDITOR / VIEWER
    REC_CRTN_TMSTP      TIMESTAMP(6) NOT NULL,

    CONSTRAINT WORKSPACE_MEMBER_PK PRIMARY KEY (WORKSPACE_MEMBER_ID),
    -- One membership row per (workspace, user); serves the authorization lookup.
    CONSTRAINT WORKSPACE_MEMBER_UK UNIQUE (WORKSPACE_ID, USER_ID),
    CONSTRAINT WORKSPACE_MEMBER_ROLE_CK CHECK (ROLE_CD IN ('OWNER', 'EDITOR', 'VIEWER')),
    CONSTRAINT WORKSPACE_MEMBER_WS_FK FOREIGN KEY (WORKSPACE_ID)
        REFERENCES NOTETAKER.WORKSPACE (WORKSPACE_ID) ON DELETE CASCADE,
    CONSTRAINT WORKSPACE_MEMBER_USER_FK FOREIGN KEY (USER_ID)
        REFERENCES NOTETAKER.APP_USER (USER_ID)
);

-- Powers "list the workspaces I belong to" without scanning all memberships.
CREATE INDEX NOTETAKER.WORKSPACE_MEMBER_IX1 ON NOTETAKER.WORKSPACE_MEMBER (USER_ID);
