CREATE TABLE NOTETAKER.WORKSPACE
(
    WORKSPACE_ID     NUMBER        GENERATED ALWAYS AS IDENTITY,
    WORKSPACE_NM     VARCHAR2(200) NOT NULL,  -- collaborative space / group name
    REC_CRTN_TMSTP   TIMESTAMP(6)  NOT NULL,
    REC_MODIFY_TMSTP TIMESTAMP(6)  NOT NULL,

    CONSTRAINT WORKSPACE_PK PRIMARY KEY (WORKSPACE_ID)
);
